/**
 * Applies the checked-in migrations to a database.
 *
 * Migrations are generated by drizzle-kit into `drizzle/` and committed, so a
 * fresh clone and a fresh machine produce byte-identical schemas without
 * anyone running a generator first.
 */

import { fileURLToPath } from "node:url";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import type { Db } from "./client";

const MIGRATIONS_FOLDER = fileURLToPath(new URL("../../../drizzle", import.meta.url));

export function runMigrations(db: Db, migrationsFolder: string = MIGRATIONS_FOLDER): void {
  migrate(db, { migrationsFolder });
}
