/**
 * Applies the checked-in migrations to a database.
 *
 * Migrations are generated by drizzle-kit into `drizzle/` and committed, so a
 * fresh clone and a fresh machine produce byte-identical schemas without
 * anyone running a generator first.
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import type { Db } from "./client";

// Assembled from parts rather than written as one URL literal, because a
// bundler reads `new URL("../../../drizzle", import.meta.url)` as a module it
// should resolve and fails the build. The ignore comment stops Turbopack's
// file tracer from reading a join that reaches the repository root as "the
// whole repository ships": this is a directory read at run time, never
// bundled.
const MIGRATIONS_FOLDER = join(
  /* turbopackIgnore: true */ dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "..",
  "drizzle",
);

export function runMigrations(db: Db, migrationsFolder: string = MIGRATIONS_FOLDER): void {
  migrate(db, { migrationsFolder });
}
